---
title: "Mosaic Global VAR"
author: "Gerry Tonkin-Hill"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 12
    fig_height: 8
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=TRUE, warning=FALSE, message=FALSE,
                      tidy=TRUE)
```



##Libraries
```{r}
library(ggplot2)
library(data.table)
library(readr)
library(dplyr)
library(stringr)

wd="/home/users/allstaff/tonkin-hill.g/mosaic_mod/reichenowi_run/"
```

##Load data
```{r}
setwd(wd)

#Isolate information file
isolateInfo <- fread("./isolateInformation.csv", data.table = FALSE)
isolateInfo <- isolateInfo[,c(1,2)]
isolateInfo$Isolate <- gsub("_.*", "", isolateInfo$Isolate)
isolateInfo$Location  <- gsub("_.*", "", isolateInfo$Location)
isolateInfo <- rbind(isolateInfo, data.frame(Isolate="SYpttt15", Location = "Ape"))
isolateInfo$Location[grepl("DD2", isolateInfo$Isolate)] <- "Lab"
isolateInfo$Location[grepl("HB3", isolateInfo$Isolate)] <- "Lab"
isolateInfo$Location[grepl("3D7", isolateInfo$Isolate)] <- "Lab"

#Proportion file
proportion <- fread("proportions.txt", data.table = FALSE)
colnames(proportion) <- c("Target", "Reference", "Proportion")
```

##Merge and summarise
```{r}
prop_merge <- merge(proportion, isolateInfo, by.x="Reference", by.y = "Isolate", all.x=TRUE)

summ_location <- prop_merge %>% group_by(Location) %>%
  summarise(
    num.isolates = n(),
    sum.prop = sum(Proportion),
    avg.proportion = mean(Proportion)
  )

summ_location$reWeighted <- summ_location$avg.proportion/sum(summ_location$avg.proportion)

```


##Plot
```{r}
summ_location$Location <- factor(summ_location$Location
                                       , levels = c("Ape", "Uganda", "Ghana", "Gabon", "Iran", "Thailand", "Peru", "FrenchGuyana", "Venezuela", "Colombia"))
gg <- ggplot(summ_location, aes(x=Location, y=reWeighted, fill=Location))
gg <- gg + geom_bar(stat = "identity")
gg <- gg + theme_bw() + theme(axis.text.x = element_text(angle = 90))
gg
```